print("Getting to Know You!")
user_name = input("What's your name? ")
fav_food = input("What's your favorite food? ")
fav_music = input("What's your favorite music? ")
user_location = input("Where do you live? ")
print()
print("You are " + user_name + ".")
print("You're probably hungry for " + fav_food + "...")
print("and you love dancing to " + fav_music + " music in " + user_location + ".")
print("Have a great day!")